name: Android CI

on:
  push:
    branches:
      - main # Убедитесь, что это соответствует вашей основной ветке (main или master)
  pull_request:
    branches:
      - main # Убедитесь, что это соответствует вашей основной ветке (main или master)

jobs:
  build:
    runs-on: ubuntu-latest # Виртуальная машина на базе Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Скачивает ваш код из репозитория

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' # Указывает версию Java. Если ваш проект старый, возможно, '11' или '8'. Если новый, может быть '21'. Проверьте в build.gradle, если есть сомнения.
        distribution: 'temurin' # Или 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # Делает gradlew исполняемым

    - name: Build debug APK
      run: ./gradlew assembleDebug # Команда для сборки отладочной версии APK

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk # Стандартный путь к сгенерированному APK
